services:
  mariadb:
    image: mariadb:10.6
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis-cache:
    image: redis:7-alpine
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:7-alpine
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:7-alpine
    volumes:
      - redis-socketio-data:/data

  frappe:
    build: .
    command: ["tail", "-f", "/dev/null"]
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - REDIS_CACHE=redis-cache:6379
      - REDIS_QUEUE=redis-queue:6379
      - REDIS_SOCKETIO=redis-socketio:6379
      - SITE_NAME=${SITE_NAME:-site1.localhost}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - DEVELOPER_MODE=${DEVELOPER_MODE:-1}
    volumes:
      - ../../:/home/frappe/frappe-bench
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  nginx:
    image: frappe/frappe-nginx:latest
    environment:
      - FRAPPE_PY=frappe:8000
      - FRAPPE_PY_SSL=frappe:8000
      - FRAPPE_SOCKETIO=frappe:9000
    ports:
      - "8080:80"
    depends_on:
      - frappe

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data: